[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config = { deno = { enable = true, lint = true } }

[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc"]
file-types = ["ts", "tsx"]
language-servers = ["deno-lsp"]
auto-format = true

[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc"]
file-types = ["js", "jsx"]
language-servers = ["deno-lsp"]
auto-format = true
